# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
development:
  adapter: postgresql
  encoding: unicode
  database: bib_citi
  host: localhost
  username: citi_biblioteca
  password: citi2015
  pool: 5
 
production:
  adapter: postgresql
  encoding: unicode
  database: bib_citi
  host: localhost
  username: citi_biblioteca
  password: citi2015
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: bib_citi
  host: localhost
  username: citi_biblioteca
  password: citi2015
  pool: 5  
 
